<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Watchlog.Data\Watchlog.Data.csproj" />
    <ProjectReference Include="..\Watchlog.Models\Watchlog.Models.csproj" />
  </ItemGroup>

</Project>
